// <auto-generated />
using System;
using Fabric.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fabric.Data.Migrations
{
    [DbContext(typeof(FabricDBContext))]
    [Migration("20230507092418_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fabric.Data.Entities.Category", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            ID = "CTGR000000",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6302),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Browse all our silk fabrics here, and use the filter to refine your options! Our evolving array of designer & Liberty deadstock silk fabrics provides an ongoing treasure hunt for many a seasoned sewist, with lots of these rolls one-of-a-kind and never to be seen again!  Whether you're looking for silk prints, georgettes, crepes, challis, twills, satins, suitings or jacquards you'll be sure to find something suitable online! Shop silk fabrics online today!",
                            Name = "Silk Fabrics",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6309),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "CTGR000001",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6347),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Browse all of our range of rayon, viscose & other cellulose fabrics here and use the filter to refine your options. Our evolving array of designer & Liberty deadstock cellulose fabrics provides an ongoing treasure hunt for many a seasoned sewist, with lots of these rolls of of a kind and never to be seen again! Whether you're looking for vintage-inspired prints, georgettes, crepes, challis, twills, satins, suitings or knitted fabrics you'll be sure to find something suitable online! Shop rayon, viscose fabrics online today!",
                            Name = "Rayon, Viscose & More",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6347),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "CTGR000002",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6365),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Browse all our merino fabrics here and use the filter to refine your options! Merino is one of the world’s oldest breeds of sheep, originating in Spain as far back as the 12th century. Merino sheep produce extremely fine and soft wool, making fabric that is breathable, moisture-wicking and suitable for all seasons as well as a huge variety of uses. Browse our huge range of merino fabrics online here, including our exclusive, ethically-made ZQ Premium Merino range in over 35 shades, along with our ever-evolving range of deadstock merino fabrics in heavyweight, activewear, textured and striped styles! Shop merino fabrics online today!",
                            Name = "Merino Fabrics",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6366),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "CTGR000003",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6374),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Browse all our linen fabrics here, and use the filter to refine your options! Here at The Fabric Store, linen is one of our favourite fibres. As well as being super easy to sew, linen fabric has a lovely earthy feel, starting off crisp but softening beautifully in time with wash and wear. The flax plant, from which linen fibres are harvested, consumes far less water than cotton and requires fewer chemicals and pesticides making it a great eco fabric choice for the environmentally conscious. Browse our huge range of linen fabrics online here, including our exclusive ranges and our ever-evolving collection of deadstock linens as well! Our exclusive ranges include certified Organic Linen, Gingham Linen, Vintage Finish Linen and Heavyweight Linen. Find an array of patterns, textures and colours in our deadstock linens too! Shop linen fabrics online today!",
                            Name = "Linen Fabrics",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6375),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "CTGR000004",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6380),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Browse our huge range of cotton fabrics here and use the filter to refine your options. This collection includes our exclusive certified Organic Cotton Sweatshirting + Rib and Upcycled Cotton ranges. Our evolving array of designer & Liberty deadstock cotton fabrics provides an ongoing treasure hunt for many a seasoned sewist, with lots of these rolls one-of-a-kind and never to be seen again! Whether you're looking for cotton prints, stripes, checks, shirtings, sateens, denims, chambrays, twills, corduroys, sateens or knitted fabrics, you'll be sure to find something suitable online! Shop cotton fabrics online today!",
                            Name = "Cotton Fabrics",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6380),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "CTGR000005",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6386),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Browse all our cotton, viscose & synthetic blend knitted fabrics here and use the filter to refine your options. This collection includes our exclusive certified Organic Cotton Sweatshirting + Rib too. Our evolving array of designer & Liberty deadstock knitted fabrics provides an ongoing treasure hunt for many a seasoned sewist, with lots of these rolls of-of-a-kind and never to be seen again! Whether you're looking for relaxed linens, super soft cottons, fluid viscose and stretchy activewear jerseys. For a casual project with flair choose our printed Liberty cotton knits, and for the cooler days, our range of sweatshirtings are ideal! Shop knitted & jersey fabric online today!",
                            Name = "Jersey & Knitted Fabrics",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6387),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Fabric.Data.Entities.Image", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("Images", (string)null);

                    b.HasData(
                        new
                        {
                            ID = "IMGE000000",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6657),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ProductID = "PRDT000000",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6659),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Url = "https://res.cloudinary.com/dhi3bjn0s/image/upload/v1683395842/Fabric/ZQ_Merino_Tumeric_Swatch_1000x1000_sixf1d.webp"
                        },
                        new
                        {
                            ID = "IMGE000001",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6670),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ProductID = "PRDT000000",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6670),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Url = "https://res.cloudinary.com/dhi3bjn0s/image/upload/v1683395881/Fabric/ZQ_Merino_Tumeric_Hang_36b686ea-16c4-447b-9426-d9ea304bf617_1000x1000_ij2rgq.webp"
                        },
                        new
                        {
                            ID = "IMGE000002",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6675),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ProductID = "PRDT000000",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6675),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Url = "https://res.cloudinary.com/dhi3bjn0s/image/upload/v1683395881/Fabric/ZQ_Merino_Tumeric_Roll_1000x1000_a9dzr7.webp"
                        },
                        new
                        {
                            ID = "IMGE000003",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6680),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ProductID = "PRDT000000",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6680),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Url = "https://res.cloudinary.com/dhi3bjn0s/image/upload/v1683395883/Fabric/ZQ_Merino_Tumeric_Ruler_2864b442-a822-45b5-a5ac-90877b38be7f_1000x1000_fvgqio.webp"
                        },
                        new
                        {
                            ID = "IMGE000004",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6685),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ProductID = "PRDT000001",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6685),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Url = "https://res.cloudinary.com/dhi3bjn0s/image/upload/v1683396716/Fabric/Pindot_Merino_Blend_Jersey_Army_Swatch_1000x1000_pn9pxf.webp"
                        },
                        new
                        {
                            ID = "IMGE000005",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6691),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ProductID = "PRDT000001",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6691),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Url = "https://res.cloudinary.com/dhi3bjn0s/image/upload/v1683396715/Fabric/Pindot_Merino_Blend_Jersey_Army_Hang_1000x1000_vyvzd0.webp"
                        },
                        new
                        {
                            ID = "IMGE000006",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6695),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ProductID = "PRDT000001",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6696),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Url = "https://res.cloudinary.com/dhi3bjn0s/image/upload/v1683396716/Fabric/Pindot_Merino_Blend_Jersey_Army_Roll_1000x1000_tqamxz.webp"
                        },
                        new
                        {
                            ID = "IMGE000007",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6700),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ProductID = "PRDT000001",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6700),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Url = "https://res.cloudinary.com/dhi3bjn0s/image/upload/v1683396716/Fabric/Pindot_Merino_Blend_Jersey_Army_Ruler_1000x1000_ai1wi2.jpg"
                        },
                        new
                        {
                            ID = "IMGE000008",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6705),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ProductID = "PRDT000002",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6705),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Url = "https://res.cloudinary.com/dhi3bjn0s/image/upload/v1683397552/Fabric/Teal_Sheer_Grid_Swatch_OO_1000x1000_yedrcg.webp"
                        },
                        new
                        {
                            ID = "IMGE000009",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6710),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ProductID = "PRDT000002",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6710),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Url = "https://res.cloudinary.com/dhi3bjn0s/image/upload/v1683397552/Fabric/Teal_Sheer_Grid_Hang_1000x1000_qjtbii.webp"
                        },
                        new
                        {
                            ID = "IMGE000010",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6715),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ProductID = "PRDT000002",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6715),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Url = "https://res.cloudinary.com/dhi3bjn0s/image/upload/v1683397552/Fabric/Teal_Sheer_Grid_Roll_1000x1000_gxqmax.webp"
                        },
                        new
                        {
                            ID = "IMGE000011",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6720),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ProductID = "PRDT000002",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6721),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Url = "https://res.cloudinary.com/dhi3bjn0s/image/upload/v1683397552/Fabric/Teal_Sheer_Grid_Ruler_1000x1000_jpi3h1.webp"
                        });
                });

            modelBuilder.Entity("Fabric.Data.Entities.Moonboard", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("Moonboards", (string)null);
                });

            modelBuilder.Entity("Fabric.Data.Entities.Order", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Fabric.Data.Entities.OrderDetail", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Metre")
                        .HasColumnType("float");

                    b.Property<string>("OrderID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("Fabric.Data.Entities.Pattern", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("Patterns", (string)null);

                    b.HasData(
                        new
                        {
                            ID = "PTRN000000",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6399),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Abstract",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6399),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "PTRN000001",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6412),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Animal",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6412),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "PTRN000002",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6418),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Check",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6418),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "PTRN000003",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6422),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Conversational",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6423),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "PTRN000004",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6475),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Floral",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6475),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "PTRN000005",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6481),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Geometric",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6481),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "PTRN000006",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6487),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Large Scale",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6487),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "PTRN000007",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6494),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Motif",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6495),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "PTRN000008",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6500),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "No Pattern",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6500),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = "PTRN000009",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6505),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Paisley",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6505),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Fabric.Data.Entities.Product", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PatternID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("Stretch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.Property<string>("WovedIn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("PatternID");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ID = "PRDT000000",
                            Active = true,
                            CategoryID = "CTGR000002",
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6540),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "// Our single jersey ZQ Premium Merino in our seasonal colour, Turmeric. This fabric is knitted from ZQ certified merino and produced just for us in our range of exclusive colours. The superfine merino fibre is spun into a single twist yarn, creating a slightly textural fabric with naturally occurring slubs throughout. The single jersey knit structure gives this fabric mechanical stretch and great drape. Beautifully soft, merino jersey is ideal for all seasons and perfect for next-to-skin basics and layering.",
                            Name = "ZQ Premium Merino - Turmeric",
                            PatternID = "PTRN000008",
                            Price = 36.0,
                            Quantity = 99.0,
                            Stretch = 0,
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6541),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 1,
                            Width = 59.0,
                            WovedIn = "Dalat City and Nam Dinh City, Vietnam"
                        },
                        new
                        {
                            ID = "PRDT000001",
                            Active = true,
                            CategoryID = "CTGR000002",
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6588),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "// This lightweight army green merino blend jersey has subtle pointelle holes, backed with a very fine plated stripe. Perfect for street and activewear for those chillier days.",
                            Name = "Pindot Merino Blend Jersey - Army",
                            PatternID = "PTRN000006",
                            Price = 18.0,
                            Quantity = 99.0,
                            Stretch = 1,
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6588),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 2,
                            Width = 47.0,
                            WovedIn = "Vietnam"
                        },
                        new
                        {
                            ID = "PRDT000002",
                            Active = true,
                            CategoryID = "CTGR000000",
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6600),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "// A deadstock silk/ cotton in teal and black. This lightweight fabric has been cleverly woven with sheer black warp striped with a  deep teal stripe, then a sheer black and teal striped weft creating a dimensional check fabric. A sheer fabric with a dry hand feel and no stretch. Ideal for shirts like the Bloom, dresses like the Paint or Ivy.",
                            Name = "Sheer Check Silk / Cotton - Teal / Black",
                            PatternID = "PTRN000002",
                            Price = 24.0,
                            Quantity = 99.0,
                            Stretch = 2,
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6600),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Weight = 1,
                            Width = 57.0,
                            WovedIn = "China"
                        });
                });

            modelBuilder.Entity("Fabric.Data.Entities.Sale", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("Fabric.Data.Entities.Setting", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SettingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Settings", (string)null);

                    b.HasData(
                        new
                        {
                            ID = "STTG000000",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6519),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            SettingType = "Width",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6520),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Value1 = "0",
                            Value2 = "49"
                        },
                        new
                        {
                            ID = "STTG000001",
                            Active = true,
                            Created = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6533),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            SettingType = "Width",
                            Updated = new DateTime(2023, 5, 7, 16, 24, 18, 725, DateTimeKind.Local).AddTicks(6533),
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Value1 = "50",
                            Value2 = "60"
                        });
                });

            modelBuilder.Entity("Fabric.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fabric.Data.Entities.Image", b =>
                {
                    b.HasOne("Fabric.Data.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductID");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fabric.Data.Entities.Moonboard", b =>
                {
                    b.HasOne("Fabric.Data.Entities.Product", "Product")
                        .WithMany("Moonboards")
                        .HasForeignKey("ProductID");

                    b.HasOne("Fabric.Data.Entities.User", "User")
                        .WithMany("Moonboards")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fabric.Data.Entities.Order", b =>
                {
                    b.HasOne("Fabric.Data.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fabric.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("Fabric.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID");

                    b.HasOne("Fabric.Data.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fabric.Data.Entities.Product", b =>
                {
                    b.HasOne("Fabric.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.HasOne("Fabric.Data.Entities.Pattern", "Pattern")
                        .WithMany("Products")
                        .HasForeignKey("PatternID");

                    b.Navigation("Category");

                    b.Navigation("Pattern");
                });

            modelBuilder.Entity("Fabric.Data.Entities.Sale", b =>
                {
                    b.HasOne("Fabric.Data.Entities.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductID");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Fabric.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Fabric.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fabric.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Fabric.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fabric.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Fabric.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Fabric.Data.Entities.Pattern", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Fabric.Data.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Moonboards");

                    b.Navigation("OrderDetails");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Fabric.Data.Entities.User", b =>
                {
                    b.Navigation("Moonboards");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
